name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: localhost # default host value for the database
      DB_DATABASE: django
      DB_PORT: 3306
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
            DB_USERNAME: ${{ env.DB_USERNAME }}
            DB_PASSWORD: ${{ env.DB_PASSWORD }}
            DB_HOST: ${{ env.DB_HOST }}
            DB_DATABASE: ${{ env.DB_DATABASE }}
            DB_PORT: ${{ env.DB_PORT }}
      run: |
        python manage.py test
